# -*- coding: utf-8 -*-
"""crawl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rnH_Oin_AMxirWC5eg2xZL83IQfmfCEY
"""

!pip install requests

from google.colab import drive
drive.mount("/content/drive")

import json
from bs4 import BeautifulSoup
import urllib
import time
import json
import os

n=int(input())
list_page = range(0,n)
for index_page in list_page:
  url='https://www.freepik.com/search?format=search&query=dog'
  header= {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) ' 
        'AppleWebKit/537.11 (KHTML, like Gecko) '
        'Chrome/23.0.1271.64 Safari/537.11',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
        'Accept-Encoding': 'none',
        'Accept-Language': 'en-US,en;q=0.8',
        'Connection': 'keep-alive'}
  request = urllib.request.Request(url=url,headers=header)

  page = urllib.request.urlopen(request).read()

soup = BeautifulSoup(page,'html.parser')
print(soup)

list_tag = soup.find_all('img')

for tag in list_tag:
  img_link = tag.get("src")
  if "dog" in img_link:
    print(img_link)

import requests
img_url = "https://img.freepik.com/free-vector/dog-breed-collection-vector_53876-17276.jpg?auto=format&h=200"
response = requests.get(img_url)

print(response.status_code)

if response.status_code:
    fp = open('xyz.png', 'wb')
    fp.write(response.content)
    fp.close()